[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "https://economiclab.co.za/:splat"
  status = 301
  force = true
  conditions = {Host = ["exmarkets.co.za", "www.exmarkets.co.za"]}

[[redirects]]
  from = "/about/cookies-policy"
  to = "/about/cookies-policy/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/cookies-policy/"
  to = "/about/cookies-policy/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/privacy-policy"
  to = "/about/privacy-policy/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/privacy-policy/"
  to = "/about/privacy-policy/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/disclaimer"
  to = "/about/disclaimer/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/disclaimer/"
  to = "/about/disclaimer/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/terms-of-use"
  to = "/about/terms-of-use/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/terms-of-use/"
  to = "/about/terms-of-use/index.html"
  status = 200
  force = true

[dev]
  framework = "#static"
  staticServerPort = 5500
