(function () {
  'use strict';

  var BEA_ENDPOINT = '/.netlify/functions/pce-data';
  var MARKET_ENDPOINT = 'https://exmarkets.netlify.app/.netlify/functions/market-data';
  var range = 1;
  var data = {};

  function all(selector) { return Array.prototype.slice.call(document.querySelectorAll(selector)); }
  function set(selector, value) { var element = document.querySelector(selector); if (element) element.textContent = value; }
  function number(value) { var parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; }
  function period(item) { return item ? item.date : 'Latest available'; }
  function change(current, previous) { return current && previous && previous.value !== 0 ? (current.value / previous.value - 1) * 100 : null; }
  function format(value, suffix) { return value === null || !Number.isFinite(value) ? 'Data currently unavailable' : (value >= 0 ? '+' : '') + value.toFixed(2) + (suffix || '%'); }
  function pair(key) { var values = data[key] || []; return { current: values[values.length - 1], previous: values[values.length - 2], yearAgo: values.length > 12 ? values[values.length - 13] : null }; }
  function valuesFor(key) { return (data[key] || []).slice(-(range === 'all' ? (data[key] || []).length : Number(range) * 12)); }
  function updateMetrics() {
    var pce = pair('pce'); var core = pair('core');
    var pceYoY = change(pce.current, pce.yearAgo); var coreYoY = change(core.current, core.yearAgo);
    set('[data-pce="pce-yoy"]', format(pceYoY)); set('[data-pce="core-yoy"]', format(coreYoY)); set('[data-pce="pce-mom"]', format(change(pce.current, pce.previous))); set('[data-pce="core-mom"]', format(change(core.current, core.previous)));
    set('[data-pce="previous-pce"]', format(change(pce.previous, data.pce[data.pce.length - 14]))); set('[data-pce="previous-core"]', format(change(core.previous, data.core[data.core.length - 14]))); set('[data-pce="period"]', period(pce.current));
    set('[data-pce="objective-pce"]', format(pceYoY)); set('[data-pce="difference"]', format(pceYoY === null ? null : pceYoY - 2, ' percentage points')); set('[data-pce="core-yoy-copy"]', format(coreYoY)); set('[data-pce="core-mom-copy"]', format(change(core.current, core.previous))); set('[data-pce="core-difference"]', format(coreYoY === null ? null : coreYoY - 2, ' percentage points'));
    var regime = pceYoY === null ? 'Data currently unavailable' : pceYoY > 2.25 ? 'Above objective' : pceYoY < 1.75 ? 'Below objective' : 'Near objective'; set('[data-pce="regime"]', regime); set('[data-pce="regime-copy"]', regime); set('[data-pce-status]', 'Latest available BEA-originated observation: ' + period(pce.current) + '. Values are retrieved through the FRED public data transport.');
  }
  function chart(keyA, keyB, monthly) {
    var a = valuesFor(keyA); var b = valuesFor(keyB); if (!a.length || !b.length) return '<p class="pce-unavailable">No current PCE data available.</p>';
    var width=900,height=270,left=48,right=18,top=20,bottom=35; var av=a.map(function(x,i){return monthly?change(x,a[i-1]):change(x,a[i-12]);}).filter(function(x){return x!==null;}); var bv=b.map(function(x,i){return monthly?change(x,b[i-1]):change(x,b[i-12]);}).filter(function(x){return x!==null;}); var vals=av.concat(bv); var min=Math.min(monthly?-1:0,Math.min.apply(Math,vals)); var max=Math.max(monthly?1:3,Math.max.apply(Math,vals)); var x=function(i){return left+i*((width-left-right)/Math.max(1,a.length-1));}; var y=function(v){return top+(max-v)*((height-top-bottom)/Math.max(1,max-min));};
    function path(items,source,cls){var points=source.map(function(item,i){return {v:monthly?change(item,source[i-1]):change(item,source[i-12]),i:i};}).filter(function(p){return p.v!==null;});return '<path class="'+cls+'" d="'+points.map(function(p,i){return (i?'L':'M')+x(p.i).toFixed(1)+' '+y(p.v).toFixed(1);}).join(' ')+'" />';}
    var labels=a.filter(function(_,i){return i===0||i===a.length-1||i%Math.max(1,Math.floor(a.length/5))===0;}).map(function(item){var i=a.indexOf(item);return '<text x="'+x(i).toFixed(1)+'" y="'+(height-10)+'" text-anchor="middle">'+item.date.slice(0,7)+'</text>';}).join(''); var target=monthly?'':'<path class="target-line" d="M'+left+' '+y(2).toFixed(1)+'H'+(width-right)+'"/><text x="'+(width-right-4)+'" y="'+(y(2)-5).toFixed(1)+'" text-anchor="end">Fed 2% objective</text>';
    return '<svg viewBox="0 0 '+width+' '+height+'" aria-label="PCE inflation chart"><line class="grid-line" x1="'+left+'" x2="'+(width-right)+'" y1="'+y(0).toFixed(1)+'" y2="'+y(0).toFixed(1)+'"/>'+target+path(a,a,'headline-line')+path(b,b,'core-line')+labels+'<text x="'+(left+4)+'" y="14">PCE</text><text x="'+(left+50)+'" y="14">Core PCE</text></svg>';
  }
  function render() { var trend=document.querySelector('#pce-trend-chart'); var momentum=document.querySelector('#pce-momentum-chart'); if(trend) trend.innerHTML=chart('pce','core',false); if(momentum) momentum.innerHTML=chart('pce','core',true); var body=document.querySelector('#pce-history-body'); if(body){var rows=valuesFor('pce').slice().reverse().map(function(item,i){var index=data.pce.indexOf(item);var c=data.core.filter(function(x){return x.date===item.date;})[0];return '<tr><th scope="row">'+item.date+'</th><td>'+format(change(item,data.pce[index-12]))+'</td><td>'+format(c?change(c,data.core[data.core.indexOf(c)-12]):null)+'</td><td>'+format(change(item,data.pce[index-1]))+'</td><td>'+format(c?change(c,data.core[data.core.indexOf(c)-1]):null)+'</td><td>'+format(change(item,data.pce[index-12])===null?null:change(item,data.pce[index-12])-2,' pp')+'</td></tr>';});body.innerHTML=rows.join('')||'<tr><td colspan="6">No current PCE data available.</td></tr>';}}
  function loadMarkets(){fetch(MARKET_ENDPOINT+'?symbols=USDIndex,XAUUSD,EURUSD,BTCUSD',{headers:{Accept:'application/json'}}).then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(quotes){var map={};(Array.isArray(quotes)?quotes:[]).forEach(function(q){map[q.id]=q;});all('[data-symbol]').forEach(function(card){var q=map[card.getAttribute('data-symbol')];if(!q||q.price==null)throw Error();card.querySelector('strong').textContent=Number(q.price).toLocaleString(undefined,{maximumFractionDigits:5});card.querySelector('small').textContent='Daily change: '+(q.changePercent==null?'unavailable':Number(q.changePercent).toFixed(2)+'%')+' | Updated: '+new Date(q.timestamp).toLocaleString();});}).catch(function(){all('[data-symbol]').forEach(function(card){card.querySelector('strong').textContent='Data currently unavailable';card.querySelector('small').textContent='Existing exMarkets quote provider unavailable';});});}
  function load(){var requested={pce:'PCEPI',core:'PCEPILFE',goods:'PCEDG',services:'PCESV',food:'PCEDA',energy:'PCDEE',spending:'PCE',realPce:'PCEC96',income:'PI',saving:'PSAVERT'};fetch(BEA_ENDPOINT+'?series='+encodeURIComponent(Object.keys(requested).map(function(key){return requested[key];}).join(','))).then(function(r){if(!r.ok)throw Error();return r.json();}).then(function(payload){var sourceData=payload.data||{};Object.keys(requested).forEach(function(key){data[key]=sourceData[requested[key]]||[];});if(!data.pce.length||!data.core.length)throw Error();updateMetrics();render();}).catch(function(){set('[data-pce-status]','PCE data could not be retrieved. No current PCE data available.');set('#pce-trend-chart','No current PCE data available.');set('#pce-momentum-chart','No current PCE data available.');});}
  all('[data-range]').forEach(function(button){button.addEventListener('click',function(){range=button.getAttribute('data-range');all('[data-range]').forEach(function(item){item.classList.toggle('is-active',item===button);});render();});}); load(); loadMarkets();
})();
